version: "3.9"
services:
  php-test:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres-test
    command: sh -c "php artisan migrate:fresh --seed && php artisan test"

  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
