version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
      POSTGRES_DB: laravel
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  dev-tools:
    build:
      context: ./docker/dev-tools
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
      - redis

volumes:
  pg_data:
